apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-wp
    spec:
      containers:
      - name: wp
        image: wordpress:php7.0
        ports:
        - name: wp-port
          containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: db-svc
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_PASSWORD
          value: welcome
---
apiVersion: v1
kind: Service
metadata:
  name: wp-svc
spec:
  ports:
  - port: 8888
    nodePort: 31005
    targetPort: wp-port
    protocol: TCP
  selector:
    app: blog-wp
  type: NodePort
        
        
        
        